# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .clustermesh import *
from .clustermesh_connection import *
from .config import *
from .deploy import *
from .get_helm_values import *
from .hubble import *
from .install import *
from .kubeproxy_free import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import littlejo_cilium.config as __config
    config = __config
else:
    config = _utilities.lazy_import('littlejo_cilium.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cilium",
  "mod": "index/clustermesh",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/clustermesh:Clustermesh": "Clustermesh"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/clustermeshConnection",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/clustermeshConnection:ClustermeshConnection": "ClustermeshConnection"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/config",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/config:Config": "Config"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/deploy",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/deploy:Deploy": "Deploy"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/hubble",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/hubble:Hubble": "Hubble"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/install",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/install:Install": "Install"
  }
 },
 {
  "pkg": "cilium",
  "mod": "index/kubeproxyFree",
  "fqn": "littlejo_cilium",
  "classes": {
   "cilium:index/kubeproxyFree:KubeproxyFree": "KubeproxyFree"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cilium",
  "token": "pulumi:providers:cilium",
  "fqn": "littlejo_cilium",
  "class": "Provider"
 }
]
"""
)
