# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'InstallCaArgs',
    'InstallCaArgsDict',
]

MYPY = False

if not MYPY:
    class InstallCaArgsDict(TypedDict):
        crt: pulumi.Input[builtins.str]
        key: pulumi.Input[builtins.str]
elif False:
    InstallCaArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class InstallCaArgs:
    def __init__(__self__, *,
                 crt: pulumi.Input[builtins.str],
                 key: pulumi.Input[builtins.str]):
        pulumi.set(__self__, "crt", crt)
        pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter
    def crt(self) -> pulumi.Input[builtins.str]:
        return pulumi.get(self, "crt")

    @crt.setter
    def crt(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "crt", value)

    @property
    @pulumi.getter
    def key(self) -> pulumi.Input[builtins.str]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "key", value)


