# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'InstallCaArgs',
]

@pulumi.input_type
class InstallCaArgs:
    def __init__(__self__, *,
                 crt: pulumi.Input[str],
                 key: pulumi.Input[str]):
        pulumi.set(__self__, "crt", crt)
        pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter
    def crt(self) -> pulumi.Input[str]:
        return pulumi.get(self, "crt")

    @crt.setter
    def crt(self, value: pulumi.Input[str]):
        pulumi.set(self, "crt", value)

    @property
    @pulumi.getter
    def key(self) -> pulumi.Input[str]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[str]):
        pulumi.set(self, "key", value)


