# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetHelmValuesResult',
    'AwaitableGetHelmValuesResult',
    'get_helm_values',
    'get_helm_values_output',
]

@pulumi.output_type
class GetHelmValuesResult:
    """
    A collection of values returned by getHelmValues.
    """
    def __init__(__self__, id=None, yaml=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if yaml and not isinstance(yaml, str):
            raise TypeError("Expected argument 'yaml' to be a str")
        pulumi.set(__self__, "yaml", yaml)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def yaml(self) -> str:
        """
        Yaml output
        """
        return pulumi.get(self, "yaml")


class AwaitableGetHelmValuesResult(GetHelmValuesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetHelmValuesResult(
            id=self.id,
            yaml=self.yaml)


def get_helm_values(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetHelmValuesResult:
    """
    Helm values of cilium

    ## Example Usage

    ```python
    import pulumi
    import pulumi_cilium as cilium
    import pulumi_local as local

    example_helm_values = cilium.get_helm_values()
    example_file = local.File("exampleFile",
        content=example_helm_values.yaml,
        filename=f"{path['module']}/values.yaml")
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cilium:index/getHelmValues:getHelmValues', __args__, opts=opts, typ=GetHelmValuesResult).value

    return AwaitableGetHelmValuesResult(
        id=pulumi.get(__ret__, 'id'),
        yaml=pulumi.get(__ret__, 'yaml'))


@_utilities.lift_output_func(get_helm_values)
def get_helm_values_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetHelmValuesResult]:
    """
    Helm values of cilium

    ## Example Usage

    ```python
    import pulumi
    import pulumi_cilium as cilium
    import pulumi_local as local

    example_helm_values = cilium.get_helm_values()
    example_file = local.File("exampleFile",
        content=example_helm_values.yaml,
        filename=f"{path['module']}/values.yaml")
    ```
    """
    ...
