// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("cilium");

/**
 * The content of kube config file (Default: ``).
 */
export declare const configContent: string | undefined;
Object.defineProperty(exports, "configContent", {
    get() {
        return __config.get("configContent");
    },
    enumerable: true,
});

/**
 * A path to a kube config file (Default: `~/.kube/config`).
 */
export declare const configPath: string | undefined;
Object.defineProperty(exports, "configPath", {
    get() {
        return __config.get("configPath");
    },
    enumerable: true,
});

/**
 * Context of kubeconfig file (Default: `default context`).
 */
export declare const context: string | undefined;
Object.defineProperty(exports, "context", {
    get() {
        return __config.get("context");
    },
    enumerable: true,
});

/**
 * Helm Release to install cilium (Default: `cilium.Install`).
 */
export declare const helmRelease: string | undefined;
Object.defineProperty(exports, "helmRelease", {
    get() {
        return __config.get("helmRelease");
    },
    enumerable: true,
});

/**
 * Namespace to install cilium (Default: `kube-system`).
 */
export declare const namespace: string | undefined;
Object.defineProperty(exports, "namespace", {
    get() {
        return __config.get("namespace");
    },
    enumerable: true,
});

