# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

configPath: Optional[str]
"""
A path to a kube config file (Default: `~/.kube/config`).
"""

context: Optional[str]
"""
Context of kubeconfig file (Default: `default context`).
"""

namespace: Optional[str]
"""
Namespace to install cilium (Default: `kube-system`).
"""

