// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cilium

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/littlejo/pulumi-cilium/sdk/go/cilium/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "cilium:index/clustermesh:Clustermesh":
		r = &Clustermesh{}
	case "cilium:index/clustermeshConnection:ClustermeshConnection":
		r = &ClustermeshConnection{}
	case "cilium:index/config:Config":
		r = &Config{}
	case "cilium:index/deploy:Deploy":
		r = &Deploy{}
	case "cilium:index/hubble:Hubble":
		r = &Hubble{}
	case "cilium:index/install:Install":
		r = &Install{}
	case "cilium:index/kubeproxyFree:KubeproxyFree":
		r = &KubeproxyFree{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:cilium" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"cilium",
		"index/clustermesh",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/clustermeshConnection",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/config",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/deploy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/hubble",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/install",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cilium",
		"index/kubeproxyFree",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"cilium",
		&pkg{version},
	)
}
