// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cilium

import (
	"context"
	"reflect"

	"github.com/littlejo/pulumi-cilium/sdk/go/cilium/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the cilium package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The content of kube config file (Default: ``).
	ConfigContent pulumi.StringPtrOutput `pulumi:"configContent"`
	// A path to a kube config file (Default: `~/.kube/config`).
	ConfigPath pulumi.StringPtrOutput `pulumi:"configPath"`
	// Context of kubeconfig file (Default: `default context`).
	Context pulumi.StringPtrOutput `pulumi:"context"`
	// Helm Release to install cilium (Default: `Install`).
	HelmRelease pulumi.StringPtrOutput `pulumi:"helmRelease"`
	// Namespace to install cilium (Default: `kube-system`).
	Namespace pulumi.StringPtrOutput `pulumi:"namespace"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:cilium", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The content of kube config file (Default: ``).
	ConfigContent *string `pulumi:"configContent"`
	// A path to a kube config file (Default: `~/.kube/config`).
	ConfigPath *string `pulumi:"configPath"`
	// Context of kubeconfig file (Default: `default context`).
	Context *string `pulumi:"context"`
	// Helm Release to install cilium (Default: `Install`).
	HelmRelease *string `pulumi:"helmRelease"`
	// Namespace to install cilium (Default: `kube-system`).
	Namespace *string `pulumi:"namespace"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The content of kube config file (Default: ``).
	ConfigContent pulumi.StringPtrInput
	// A path to a kube config file (Default: `~/.kube/config`).
	ConfigPath pulumi.StringPtrInput
	// Context of kubeconfig file (Default: `default context`).
	Context pulumi.StringPtrInput
	// Helm Release to install cilium (Default: `Install`).
	HelmRelease pulumi.StringPtrInput
	// Namespace to install cilium (Default: `kube-system`).
	Namespace pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:cilium/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The content of kube config file (Default: “).
func (o ProviderOutput) ConfigContent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ConfigContent }).(pulumi.StringPtrOutput)
}

// A path to a kube config file (Default: `~/.kube/config`).
func (o ProviderOutput) ConfigPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ConfigPath }).(pulumi.StringPtrOutput)
}

// Context of kubeconfig file (Default: `default context`).
func (o ProviderOutput) Context() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Context }).(pulumi.StringPtrOutput)
}

// Helm Release to install cilium (Default: `Install`).
func (o ProviderOutput) HelmRelease() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.HelmRelease }).(pulumi.StringPtrOutput)
}

// Namespace to install cilium (Default: `kube-system`).
func (o ProviderOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Namespace }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
