# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('cilium')


class _ExportableConfig(types.ModuleType):
    @property
    def config_content(self) -> Optional[str]:
        """
        The content of kube config file (Default: ``).
        """
        return __config__.get('configContent')

    @property
    def config_path(self) -> Optional[str]:
        """
        A path to a kube config file (Default: `~/.kube/config`).
        """
        return __config__.get('configPath')

    @property
    def context(self) -> Optional[str]:
        """
        Context of kubeconfig file (Default: `default context`).
        """
        return __config__.get('context')

    @property
    def helm_release(self) -> Optional[str]:
        """
        Helm Release to install cilium (Default: `Install`).
        """
        return __config__.get('helmRelease')

    @property
    def namespace(self) -> Optional[str]:
        """
        Namespace to install cilium (Default: `kube-system`).
        """
        return __config__.get('namespace')

