
name: build

on:
  pull_request:
    paths-ignore:
      - docs
      - .devcontainer
      - examples

jobs:
  build_sdk:
    name: build_sdk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
          - 6.0.x
        goversion:
          - 1.23.x
        nodeversion:
          - 20.x
        pythonversion:
          - "3.11"
        javaversion:
          - "11"
        language:
          - nodejs
          - python
          - go
          #- dotnet
          # - java

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.goversion}}

    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
        repo: pulumi/pulumictl

    - name: Install pulumi
      uses: pulumi/actions@v6

    - if: ${{ matrix.language == 'nodejs'}}
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: https://registry.npmjs.org

    - if: ${{ matrix.language == 'dotnet'}}
      name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnetversion}}

    - if: ${{ matrix.language == 'python'}}
      name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.pythonversion}}

    - if: ${{ matrix.language == 'java'}}
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{matrix.javaversion}}

    - name: Build SDK
      run: make build_${{ matrix.language }}

    - name: Check worktree clean
      run: |
        git update-index -q --refresh
        if ! git diff-files --quiet; then
            git status
            git diff
            #exit 1
        fi
        git checkout provider/cmd/pulumi-resource-cilium/schema.json
        if ! git diff-files --quiet; then
            >&2 echo "error: working tree is not clean, aborting!"
            git status
            git diff
            exit 1
        fi

  goreleaser:
    name: goreleaser-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.goversion}}

    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
        repo: pulumi/pulumictl

    - name: Set PreRelease Version
      run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@006a7a4111c6a1b44a25a1f3d23f0c8d940ad847
      with:
        args: check
    strategy:
      fail-fast: true
      matrix:
        goversion:
          - 1.23.x

  test:
    name: "Functionnal test: Install Cilium on one cluster"
    runs-on: ubuntu-latest
    env:
      dir: .github/pulumi/yaml/simple
      PULUMI_CONFIG_PASSPHRASE: ""
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        goversion:
          - 1.23.x
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.goversion}}
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
        repo: pulumi/pulumictl
    - name: Install pulumi
      uses: pulumi/actions@v6
    - name: Build provider
      run: make provider
    - name: Setup kind test1
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        wait: 0
        config: .github/config/acceptance_tests_kind_config.yaml
        cluster_name: "test1"
    - name: Install cilium
      run: |
        pulumi login --local
        pulumi stack init dev
        pulumi up --stack dev -y
      working-directory: ${{ env.dir }}
    - uses: cilium/cilium-cli@ea870caf33eeefaf7587f708538b779b3c7cca2d
      with:
        skip-build: true
        release-version: v0.16.10
    - name: Check cilium
      run: |
        cilium status --wait
