// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Helm values of cilium
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cilium from "@pulumi/cilium";
 * import * as local from "@pulumi/local";
 *
 * const exampleHelmValues = cilium.getHelmValues({});
 * const exampleFile = new local.File("exampleFile", {
 *     content: exampleHelmValues.then(exampleHelmValues => exampleHelmValues.yaml),
 *     filename: `${path.module}/values.yaml`,
 * });
 * ```
 */
export function getHelmValues(opts?: pulumi.InvokeOptions): Promise<GetHelmValuesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cilium:index/getHelmValues:getHelmValues", {
    }, opts);
}

/**
 * A collection of values returned by getHelmValues.
 */
export interface GetHelmValuesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Yaml output
     */
    readonly yaml: string;
}
/**
 * Helm values of cilium
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cilium from "@pulumi/cilium";
 * import * as local from "@pulumi/local";
 *
 * const exampleHelmValues = cilium.getHelmValues({});
 * const exampleFile = new local.File("exampleFile", {
 *     content: exampleHelmValues.then(exampleHelmValues => exampleHelmValues.yaml),
 *     filename: `${path.module}/values.yaml`,
 * });
 * ```
 */
export function getHelmValuesOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetHelmValuesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cilium:index/getHelmValues:getHelmValues", {
    }, opts);
}
